### ISSUE TITLE
Update the readme

### ISSUE THREAD

**Issue by Prabesh-Shrestha** [Prabesh-Shrestha/todo_rs#2]
remake the readme file and add the necessary content, like the description of the project, how to contribute and how to use it, and prettify the looks too.

**Comment by Prabesh-Shrestha** [comment]
sure @najeebkp , go ahead, i really liked your previous one

**Comment by najeebkp** [comment]
@Prabesh-Shrestha please provide screenshots if available.

**Comment by Prabesh-Shrestha** [comment]
sure

**Comment by Prabesh-Shrestha** [comment]
![image](https://user-images.githubusercontent.com/65012735/196863628-3b107367-58ae-4c31-bfa5-a1d51a94e114.png)
here you go @najeebkp

**Comment by Prabesh-Shrestha** [comment]
thank you for your contribution @najeebkp
